---
title: "দারসুল কুরআন (সুরাহ সফ (১-৯)"
author: আহমদ বিন রফিক 
date: \today
output: 
  revealjs::revealjs_presentation:
    theme: sky
    reveal_plugins: ["chalkboard", "zoom", "menu"]
    self_contained: false
    css: css/styles.css
    includes:
      in_header: css/header.html
---

# সুরা সফ (১-৯)

## আরবি 

[আরবি আয়াত দেখতে ক্লিক করুন](https://tanzil.net/#61:1)

## অর্থ (১-৪ ) 

1. আসমান ও যমীনে যা কিছু আছে তা সবই আল্লাহর তাসবীহ করছে। তিনি মহাপরাক্রমশালী ও মহাজ্ঞানী।
2. হে মু’মিনগণ! তোমরা এমন কথা কেন বল যা নিজেরা করো না?
3. আল্লাহর কাছে এটা অত্যন্ত অপছন্দনীয় কাজ যে, তোমরা এমন কথা বলো যা করো না।
4. আল্লাহ সেই সব লোকদের ভালবাসেন যারা তাঁর পথে এমনভাবে কাতারবন্দী হয়ে লড়াই করে যেন তারা সীসা গলিয়ে ঢালাই করা এক মজবুত দেয়াল।

## অর্থ (৫-৬) 

5. তোমরা মূসার সেই কথাটি স্মরণ করো যা তিনি তাঁর কওমকে বলেছিলেন। “হে আমার কাওমের লোক, তোমরা কেন আমাকে কষ্ট দাও? অথচ তোমরা ভাল করেই জানো যে, আমি তোমাদের জন্য আল্লাহর প্রেরিত রসূল। এরপর যেই তারা বাঁকা পথ ধরলো অমনি আল্লাহও তাদের দিল বাঁকা করে দিলেন। আল্লাহ‌ কাফেকদের হিদায়াত দান করেন না।
6. আর স্মরণ করো ঈসা ইবনে মারয়ামের সেই কথা যা তিনি বলেছিলেনঃ হে বনী ইসরাঈল, আমি তোমাদের কাছে আল্লাহর প্রেরিত রসূল। আমি সেই তাওরাতের সত্যতা প্রতিপাদনকারী যা আমার পূর্বে এসেছে এবং একজন রসূলের সুসংবাদদাতা যিনি আমার পরে আসবেন, যার নাম আহমাদ। কিন্তু যখন তিনি তাদের কাছে সুস্পষ্ট প্রমাণ পেশ করলেন তখন তারা বললঃ এটা তো স্পষ্ট প্রতারণা।

## অর্থ (৮-৯) 

7. সেই ব্যক্তির চেয়ে বড় জালেম আর কে হবে যে আল্লাহর বিরুদ্ধে মিথ্যা বানিয়ে বলে।  অথচ তাকে শুধু ইসলামের (আল্লাহর আনুগত্য করার) দিকে আহ্বান করা হচ্ছে। আল্লাহ এ রকম জালেমদের হিদায়াত দেন না।
8. এরা তাদের মুখের ফুঁ দিয়ে আল্লাহর নূরকে নিভিয়ে দিতে চায়। অথচ আল্লাহর ফায়সালা হলো তিনি তার নূরকে পূর্ণরূপে বিকশিত করবেন। কাফেররা তা যতই অপছন্দ করুক না কেন।
9. তিনিই সেই মহান সত্তা যিনি তাঁর রসূলকে হিদায়াত এবং ‘দ্বীনে হক’ দিয়ে পাঠিয়েছেন যাতে তিনি এ দ্বীনকে অন্য সকল দ্বীনের ওপর বিজয়ী করেন, চাই তা মুশরিকদের কাছে যতই অসহনীয় হোক না কেন।

## নামকরণ 

সূরার চতুর্থ আয়াতের يُقَاتِلُونَ فِي سَبِيلِهِ صَفًّا আয়াতাংশ থেকে এর নাম গৃহীত হয়েছে। 

নামের অর্থ: কাতার বা সারি। 

## নাযিলের সময়কাল 

কোন নির্ভরযোগ্য বর্ণনা থেকে এর নাযিল হওয়ার সময়-কাল জানা যায় না। কিন্তু এর বিষয়বস্তু নিয়ে চিন্তা-ভাবনা করলে অনুমান করা যায় যে, সূরাটি সম্ভবত ওহোদ যুদ্ধের সমসাময়িককালে নাযিল হয়ে থাকবে। কারণ এর মধ্যে যেসব পরিবেশ-পরিস্থিতির প্রতি ইঙ্গিত রয়েছে। তা সেই সময়ের সাথেই সংশ্লিষ্ট।

# ব্যাখ্যা 

# আল্লাহ দোষ-ত্রুটি থেকে পবিত্র 

## এমন ঘোষণা দিয়ে শুরু আয়াত 

سَبَّحَ (পবত্রিতা ঘোষণা করেছে) - ৫৭ (হাদিদ), ৫৯ (হাশর), ৬১ (সফ)  

يُسَبِّحُ ((পবত্রিতা ঘোষণা করছে এবং করবে)- ৬২ (জুমুআ), ৬৪ (তাগাবুন)  

سَبِّحِ (পবিত্রতা ঘোষণা করুন) - ৮৭ (আলা) 

## ঘোষণার তাৎপর্য 

সমস্ত দোষ ত্রুটির উর্ধ্বে। 

> - মহাবিশ্বের সবকিছু এর সাক্ষ্য দিচ্ছে। কোথাও কোনো ভুল নেই। 
> -  [সুরা মুলক ৬৭:৩-৪](https://tanzil.net/#67:3)
> - মানবজীবনেও তাঁর নিয়ম ও আইন মেনে চললেই মহাবিশ্বের মতো শৃঙ্খলা 

# আযীয ও হাকিম 

অল্প কিছু জায়গায় জালেমদের ব্যাপারে قوى (নিরংকুশ শক্তির অধিকারী), مقتدر (ক্ষমতাধর), جبار (আপন নির্দেশাবলী বাস্তবায়নকারী) এবং ذوانتقام (প্রতিশোধ গ্রহণকারী)

তবে رحيم রহিম (দয়ালু, নিয়মতদানকারী), غفور গাফূর (ক্ষমাশীল) কথাগুলোই বেশি। 

> - যিনি এত ক্ষমতাধর তিনি আবার মূর্খ , জালিম বা বোকাও নন। ক্ষমাশীল ও জ্ঞানী। অতএব তিনিই বিধানদাতা হবার যোগ্য। 

# যা বলা তা না করা 

> - অন্যায় কাজ না হলে কসম পূরণ করতে হবে (অন্যায় কাজে কাফফারা দিতে হবে। ৫:৮৯) 
> - মুনাফিকের লক্ষণ 
> - জিহাদের ব্যাপারের মদিনার মুনিফিকরা এমন করেছিল 
> - নিসা [৪:৭৭], মুহাম্মাদ [৪৭:২০], [আলে ইমরান](১৩ থেকে ১৭ রুকু) , আলে ইমরান ৩:১৬৭ 

