---
title: "Bible Notes"
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

\newpage
\fontsize{13}{22}
\fontseries{n}
\selectfont

\newpage

# Conventions

## Different Versions

The Bible has got many versions. I have used New International Version (NIV) and King James Version (KJV) most frequently, not because different versions serve my purpose, but because I am more used to the language of the specific versions. 

## Acronyms

KJV = King James Version 

NIV = New International Version

# Introduction

## What is Bible?

The Bible is a collection of books comprising of 39 books in Old Testament and 27 books in the New Testament, totaling 66. The Roman Catholic Bible has 73 books. 

## The Apostles

**Gospel of Mathew (10:2-5)**

The names of the twelve apostles are these; The first, **Simon**, who is called Peter, and **Andrew** his brother; **James** the son of Zebedee, and **John** his brother;

3 **Philip**, and **Bartholomew**; **Thomas**, and **Matthew** the publican; **James** the son of Alphaeus, and **Lebbaeus**, whose surname was Thaddaeus;

4 **Simon** the Canaanite, and **Judas Iscariot**, who also betrayed him.

5 These twelve Jesus sent forth, and commanded them, saying, Go not into the way of the Gentiles, and into any city of the Samaritans enter ye not:


# Concept of God

### The First Commandment

> And one of the scribes came, ... asked him,  Which is the first commandment of all? 29 And Jesus answered him, The first of all the commandments is, Hear, O Israel; **The Lord our God is one Lord** (Shema Yisrael, Adonai eloheinu, Adonai echad). 
>
> --- [KJV, Mark 12:28- 29](https://www.biblegateway.com/passage/?search=Mark%2012&version=KJV)

### God is One

> Hear, O Israel: The Lord our God is one Lord: 
>
> --- [KJV, Deuteronomy 6:4](Deuteronomy)

> For thou shalt worship no other god: for the Lord, whose name is Jealous, is a jealous God:
>
> --- [Exodus 34:14 (KJV)](https://www.biblegateway.com/passage/?search=Exodus%2034&version=KJV)



**Book of Exodus Ch 20**

3 Thou shalt have **no other gods** before me.

4 Thou shalt not make unto thee any **graven image, or any likeness of any thing** that is in heaven above, or that is in the earth beneath, or that is in the water under the earth.

5 Thou shalt not bow down thyself to them, nor serve them: for I the Lord thy God am a jealous God

> Now this is eternal life: that they know you, **the only true God**, and Jesus Christ, **whom you have sent**. 
>
> --- [NIV, John 17:3](https://www.biblegateway.com/passage/?search=John+17&version=NIV)

> I, even I, am the Lord; and beside me there is no saviour. 
>
> --- [Isaiah 43:11 (KJV)](https://www.biblegateway.com/passage/?search=Isaiah%2043&version=KJV)

> I am the Lord, and there is none else, there is **no God beside me**...
>
> --- [Isaiah 45:5](https://www.biblegateway.com/passage/?search=Isaiah%2045&version=KJV)

### Only God is good

> 18 And a certain ruler asked him, saying, Good Master, what shall I do to inherit eternal life? 19 And Jesus said unto him, Why callest thou me good? none is good, save one, that is, God. [**(KJV, Luke 18:18-19)**](https://www.biblegateway.com/passage/?search=Luke%2018&version=KJV)

# Divinity of Jesus

## I and Father One Explanation

Christians, to prove Jesus (PBUH) was God, quote John 10:30

> I and my Father are one. (John 10:30)

The context is important, which goes like this, starting from the 22nd verse of the 10th chapter:

22 And it was at Jerusalem the feast of the dedication, and it was winter. 

23 And Jesus walked in the temple in Solomon's porch. 

24 Then came the Jews round about him, and said unto him, How long dost thou make us to doubt? If thou be the Christ, tell us plainly. 

25 Jesus answered them, I told you, and ye believed not: the works that I do in my Father's name, they bear witness of me. 

26 But ye believe not, because ye are not of my sheep, as I said unto you. 

27 My sheep hear my voice, and I know them, and they follow me: 

28 and I give unto them eternal life; and they shall never perish, neither shall any man pluck them out of my hand. 

29 My Father, which gave them me, is greater than all; and no man is able to pluck them out of my Father's hand. 

30 \textbf{I and my Father are one.}

31 Then the Jews took up stones again to stone him. 

32 Jesus answered them, Many good works have I showed you from my Father; for which of those works do ye stone me? 

33 The Jews answered him, saying, For a good work we stone thee not; but for blasphemy; and because that thou, being a man, makest thyself God. 

34 Jesus answered them, \textbf{Is it not written in your law, I said, Ye are gods?} 

35 If he called them gods, unto whom the word of God came, and the scripture cannot be broken; 

36 say ye of him, whom the Father hath sanctified, and sent into the world, Thou blasphemest; because I said, I am the Son of God? 

37 If I do not the works of my Father, believe me not. 

38 But if I do, though ye believe not me, believe the works: that ye may know, and believe, that the Father is in me, and I in him.


39 Therefore they sought again to take him: but he escaped out of their hand, 

40 and went away again beyond Jordan into the place where John at first baptized; and there he abode. 

41 And many resorted unto him, and said, John did no miracle: but all things that John spake of this man were true. 

42 And many believed on him there.

## I am the way

> Jesus answered, “I am the way and the truth and the life. No one comes to the Father except through me. (NIV, John 14:6) [^1]

Again, read the context the understand the meaning, beginning from the first verse. 

1 Do not let your hearts be troubled. You believe in God; believe also in me. 

2 My Father’s house has many rooms; if that were not so, would I have told you that I am going there to prepare a place for you? 

3 And if I go and prepare a place for you, I will come back and take you to be with me that you also may be where I am. 

4 You know the way to the place where I am going.”

5 Thomas said to him, “Lord, we don’t know where you are going, so how can we know the way?”

6 Jesus answered, \textbf{“I am the way and the truth and the life. No one comes to the Father except through me.}

7 If you really know me, you will know my Father as well. From now on, you do know him and have seen him.”

8 Philip said, “Lord, show us the Father and that will be enough for us.”

9 Jesus answered: “Don’t you know me, Philip, even after I have been among you such a long time? Anyone who has seen me has seen the Father. How can you say, ‘Show us the Father’?

10 Don’t you believe that **I am in the Father, and that the Father is in me?** The words I say to you I do not speak on my own authority. Rather, it is the Father, living in me, who is doing his work. 

11 Believe me when I say that I am in the Father and the Father is in me; or at least believe on the evidence of the works themselves. 

12 Very truly I tell you, whoever believes in me will do the works I have been doing, and they will do even greater things than these, because I am going to the Father. 

13 And I will do whatever you ask in my name, so that the Father may be glorified in the Son. 

14 You may ask me for anything in my name, and I will do it.

15 “**If you love me, keep my commands.** 

16 And I will ask the Father, and he will give you another advocate to help you and be with you forever— 

17 the Spirit of truth. The world cannot accept him, because it neither sees him nor knows him. But you know him, for he lives with you and will be in you. 

18 I will not leave you as orphans; I will come to you. 

19 Before long, the world will not see me anymore, but you will see me. Because I live, you also will live. 

20 On that day you will realize that **I am in my Father, and you are in me, and I am in you.** 

21 Whoever has my commands and keeps them is the one who loves me. The one who loves me will be loved by my Father, and I too will love them and show myself to them.”

**If the Verse 10 means Jesus (PBUH) is God, then does the Verse 20 mean the disciples are also God? This would render Christianity like pantheism.**


## Jesus (PBUH) a Messenger

> the Father is greater than I [***(NIV, John 14:28)***](https://www.biblegateway.com/passage/?search=John%2014&version=NIV)

> My Father is greater than all [(NIV, John 14:28)](https://www.biblegateway.com/passage/?search=John%2010&version=NIV)

> It is by the Spirit of God that I drive out demons [***(NIV, Matthew 12 12:28)***](https://www.biblegateway.com/passage/?search=Matthew%2012&version=NIV)

> I drive out demons by the finger of God [***(NIV, Luke 11:20)***](https://www.biblegateway.com/passage/?search=Luke%2011&version=NIV)

> Anyone who does not love me will not obey my teaching. These words you hear are not my own; they belong to the Father who sent me. [***(NIV, John 14:24)***](https://www.biblegateway.com/passage/?search=John%2014%3A24&version=NIV)

> The words I say to you I do not speak on my own authority. Rather, it is the Father [***(NIV, John 14:10)***](https://www.biblegateway.com/passage/?search=John%2014%3A10&version=NIV)

> I can of mine own self do nothing: as I hear, I judge: and my judgment is just; because I seek not mine own will, but the will of the Father which hath sent me. [**(KJV, John 5:30)**](https://www.biblegateway.com/passage/?search=John+5%3A30&version=KJV)

> Now this is eternal life: that they know you, **the only true God**, and Jesus Christ, **whom you have sent**. [**(NIV, John 17:3)**](https://www.biblegateway.com/passage/?search=John+17&version=NIV)

> Ye men of Israel, hear these words; Jesus of Nazareth, **a man approved of God** among you by miracles and wonders and signs, which **God did by him** in the midst of you, as ye yourselves also know [**(KJV, Acts 2:22)**](https://www.biblegateway.com/passage/?search=Acts%202&version=KJV)

# Teachings

## Follow the commands

> If you love me, **keep my commands.** (NIV, John 14:15)

> Whoever has **my commands and keeps them is the one who loves me**. The one who loves me will be loved by my Father, and I too will love them and show myself to them. (NIV, John 14:21) 

> Jesus replied, “Anyone **who loves me will obey my teaching**. My Father will love them, and we will come to them and make our home with them. 24 Anyone **who does not love me will not obey my teaching**. These words you hear are not my own; they belong to the Father who sent me." [(NIV, John 14:23-24)](https://www.biblegateway.com/passage/?search=John%2014&version=NIV)

> Think not that I am come to destroy the law, or the prophets: I am not come to destroy, but to fulfil. 18 For verily I say unto you, **Till heaven and earth pass, one jot or one tittle shall in no wise pass from the law**, till all be fulfilled. 19 Whosoever therefore shall **break one of these least commandments**, and shall teach men so, he shall be called the **least in the kingdom of heaven**: but whosoever shall do and teach them, the same shall be called great in the kingdom of heaven. 20 For I say unto you, That except your righteousness shall exceed the righteousness of the scribes and Pharisees, ye shall in **no case enter into the kingdom of heaven**. [(KJV, Matthew 5:17-20)](https://www.biblegateway.com/passage/?search=Matthew%205&version=KJV)

## Jesus (PBUH) Was Sent to The Jews

> Go not into the way of the Gentiles, and into any city of the Samaritans enter ye not: 6 But go rather to the lost sheep of the house of Israel.
>
> --- [Mathew 10:5-6](https://www.biblegateway.com/passage/?search=Matthew%2010&version=KJV)

> I am not sent but unto the lost sheep of the house of Israel.
>
> --- [Mathew 15:24](https://www.biblegateway.com/passage/?search=Matthew+15&version=KJV)

# Muhammad (PBUH) in Bible

Gospel of John, Chapter 14

> 16 And I will ask the Father, and he will give you another advocate to help you and be with you forever— 17 the Spirit of truth. The world cannot accept him, because it neither sees him nor knows him. But you know him, for he lives with you and will in you. (NIV, John 14:16-17)

# References

[^1]: https://www.biblegateway.com/passage/?search=John%2014%3A6&version=NIV