---
title: "Quranic Arabic"
author: Ahmad Bin Rafiq
date: \today
output: 
  revealjs::revealjs_presentation:
    theme: sky
    reveal_plugins: ["menu", "chalkboard", "zoom"]
    self_contained: false
    css: css/styles.css
    includes:
      in_header: css/header.html
---

# Importance of Arabic  

## Quran is Easy to Understand

# One-letter Words

## Alif

Meaning: কি / Is / Will etc.

> - 2:13  قَالُوا أَنُؤْمِنُ كَمَا آمَنَ السُّفَهَاءُ ۗ
> - 2:140  قُلْ أَأَنتُمْ أَعْلَمُ أَمِ اللَّهُ 
> - 27:61-64 أَإِلَٰهٌ مَّعَ اللَّهِ 
> - 6:30 قَالَ أَلَيْسَ هَٰذَا بِالْحَقِّ ۚ
> - 7:172  أَلَسْتُ بِرَبِّكُمْ
> - 95:8 أَلَيْسَ اللَّهُ بِأَحْكَمِ الْحَاكِمِينَ 
> - 75: 36 أَيَحْسَبُ الْإِنسَانُ أَن يُتْرَكَ سُدًى
> - More: https://tanzil.net/#search/root/%D8%A7


## Ba (ب)

Meanings: with, to, (am/is/are), about, for/because of,

> - بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
> - 2:3  الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ 
> - 2: 26 يُضِلُّ بِهِ كَثِيرًا وَيَهْدِي بِهِ كَثِيرًا ۚ 
> - 3:37 إِنَّ اللَّهَ يَرْزُقُ مَن يَشَاءُ بِغَيْرِ حِسَابٍ 
> - 3: 63 فَإِن تَوَلَّوْا فَإِنَّ اللَّهَ عَلِيمٌ بِالْمُفْسِدِينَ 
> - 4:153 فَأَخَذَتْهُمُ الصَّاعِقَةُ بِظُلْمِهِمْ ۚ
> - 7: 105  قَدْ جِئْتُكُم بِبَيِّنَةٍ مِّن رَّبِّكُمْ
> - 64:111 مَا أَصَابَ مِن مُّصِيبَةٍ إِلَّا بِإِذْنِ اللَّ
> - 95:8 أَلَيْسَ اللَّهُ بِأَحْكَمِ الْحَاكِمِينَ 
> - More: https://tanzil.net/#search/root/%D8%A8

## Sin (س)

Meanings: Of course, soon

> - 2:58 وَسَنَزِيدُ الْمُحْسِنِينَ
> - 28:27 سَتَجِدُنِي إِن شَاءَ اللَّهُ مِنَ الصَّالِحِينَ
> - 68: 5 فَسَتُبْصِرُ وَيُبْصِرُونَ
> - More: https://tanzil.net/#search/root/%D8%B3

## Fa (ف)

Meanings: Therefore, then, but, afterwards

> - 2: 18  صُمٌّ بُكْمٌ عُمْيٌ فَهُمْ لَا يَرْجِعُونَ
> - 3: 144  أَفَإِن مَّاتَ أَوْ قُتِلَ انقَلَبْتُمْ عَلَىٰ أَعْقَابِكُمْ
> - 6:48 فَمَنْ آمَنَ وَأَصْلَحَ فَلَا خَوْفٌ عَلَيْهِمْ 
> - 35: 3 فَأَنَّىٰ تُؤْفَكُونَ
> - 55: 69  فَبِأَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ
> - 68: 5 فَسَتُبْصِرُ وَيُبْصِرُونَ
> - More: https://tanzil.net/#search/root/%D9%81/

## Kaf (ك)

Meanings: You, your; like/similar to, মত

> - 2:4 وَالَّذِينَ يُؤْمِنُونَ بِمَا أُنزِلَ إِلَيْكَ
> - 7: 179 ولَٰئِكَ كَالْأَنْعَامِ
> - 20:132 نَّحْنُ نَرْزُقُكَ ۗ
> - 21: 107  وَمَا أَرْسَلْنَاكَ إِلَّا رَحْمَةً لِّلْعَالَمِينَ
> - 38: 77 قَالَ فَاخْرُجْ مِنْهَا فَإِنَّكَ رَجِيمٌ
> - 23: 97 وَقُل رَّبِّ أَعُوذُ بِكَ مِنْ هَمَزَاتِ الشَّيَاطِينِ
> - 39: 30  إِنَّكَ مَيِّتٌ وَإِنَّهُم مَّيِّتُونَ
> - 41: 39 وَمِنْ آيَاتِهِ أَنَّكَ تَرَى الْأَرْضَ خَاشِعَةً
> - More: https://tanzil.net/#search/root/%D9%83/

## Lam (ل)

Meanings: for, to, belongs to , so that; matter; certainly, befitting, শোভনীয় 

> - 1:2 الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
> - 2: 10 وَلَهُمْ عَذَابٌ أَلِيمٌ 
> - 3: 79  مَا كَانَ لِبَشَرٍ أَن يُؤْتِيَهُ اللَّهُ الْكِتَابَ وَالْحُكْمَ وَالنُّبُوَّةَ ثُمَّ يَقُولَ لِلنَّاسِ كُونُوا عِبَادًا لِّي مِن دُونِ اللَّهِ
> - 33: 21 لَّقَدْ كَانَ لَكُمْ فِي رَسُولِ اللَّهِ أُسْوَةٌ حَسَنَةٌ لِّمَن كَانَ يَرْجُو اللَّهَ وَالْيَوْمَ الْآخِرَ وَذَكَرَ اللَّهَ كَثِيرًا 
> - 24: 30 قُل لِّلْمُؤْمِنِينَ يَغُضُّوا مِنْ أَبْصَارِهِمْ 
> - 33:36 وَمَا كَانَ لِمُؤْمِنٍ وَلَا مُؤْمِنَةٍ إِذَا قَضَى اللَّهُ وَرَسُولُهُ أَمْرًا أَن يَكُونَ لَهُمُ الْخِيَرَةُ مِنْ أَمْرِهِمْ
> - 68: 4 وَإِنَّكَ لَعَلَىٰ خُلُقٍ عَظِيمٍ
> - More: https://tanzil.net/#search/root/%D9%84

## Ha/Hu (ه)

Meanings: He, him, his, it, its, সে, তার, তাকে,এটা, এটার, এটাকে 

> - 2:2  لَا رَيْبَ ۛ فِيهِ
> - 5:72 إِنَّهُ مَن يُشْرِكْ بِاللَّهِ فَقَدْ حَرَّمَ اللَّهُ عَلَيْهِ الْجَنَّةَ 
> - 6:18  وَهُوَ الْقَاهِرُ فَوْقَ عِبَادِهِ
> - 6:36  ثُمَّ إِلَيْهِ يُرْجَعُونَ
> - 17:2 وَآتَيْنَا مُوسَى الْكِتَابَ وَجَعَلْنَاهُ هُدًى لِّبَنِي إِسْرَائِيلَ
> - 52:39  أَمْ لَهُ الْبَنَاتُ وَلَكُمُ الْبَنُونَ
> - https://tanzil.net/#search/root/%D9%87/

## Ya (ى)

Meanings: Me, My, Mine , আমি, আমার 

> - 2:124 قَالَ إِنِّي جَاعِلُكَ لِلنَّاسِ إِمَامًا
> - 2:124 قَالَ وَمِن ذُرِّيَّتِي ۖ
> - 2:124 قَالَ لَا يَنَالُ عَهْدِي الظَّالِمِينَ
> - 6:79 إِنِّي وَجَّهْتُ وَجْهِيَ 
> - 6:162 قُلْ إِنَّ صَلَاتِي وَنُسُكِي وَمَحْيَايَ وَمَمَاتِي لِلَّهِ
> - 14:7 إِنَّ عَذَابِي لَشَدِيدٌ 

# Past Tense

Starts with zabar, usually 3 letters

> - Ends with tu: I did
> - خَلَقْتُ ,
> - Ends with naa: We did 
> - Ends with ta () : You did
> - أَنْعَمْتَ, 
> - tuma/tum: You (pl) did 
> - Others: فَرَضَ اللَّ, جَعَلَ, 

## First Person

تُ = I did, نَا = We did 

> - 2:34 وَإِذْ قُلْنَا لِلْمَلَائِكَةِ 
> - 2:38 وَآمِنُوا بِمَا أَنزَلْتُ
> - 2:47 أَنْعَمْتُ عَلَيْكُمْ 
> - 2:50 وَإِذْ فَرَقْنَا بِكُمُ الْبَحْرَ
> - 5:3 الْيَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ
> - 12: 1 إِنَّا أَنزَلْنَاهُ قُرْآنًا عَرَبِيًّا
> - 14:5 وَلَقَدْ أَرْسَلْنَا مُوسَىٰ 
> - 51:56 وَمَا خَلَقْتُ الْجِنَّ وَالْإِنسَ إِلَّا لِيَعْبُدُونِ 
> - 71:5 قَالَ رَبِّ إِنِّي دَعَوْتُ قَوْمِي
> - 71:7 كُلَّمَا دَعَوْتُهُمْ

## Third Person 

> - 2:34 فَسَجَدُوا إِلَّا إِبْلِيسَ
> - 2:37 فَتَابَ عَلَيْهِ
> - 3:3 نَزَّلَ عَلَيْكَ الْكِتَابَ
> - 3:4 وَأَنزَلَ الْفُرْقَانَ
> - 14:7 جَاءَتْهُمْ رُسُلُهُم
> - 14:10  أَفِي اللَّهِ شَكٌّ فَاطِرِ السَّمَاوَاتِ وَالْأَرْضِ
> - 71:14 وَقَدْ خَلَقَكُمْ 
> - 71: 15 خَلَقَ اللَّهُ سَبْعَ سَمَاوَاتٍ
> - 98:7 إِنَّ الَّذِينَ آمَنُوا
> - 98:7 وَعَمِلُوا الصَّالِحَاتِ
> - 98:1  الَّذِينَ كَفَرُوا 

## Second Person

> - 2:6 سَوَاءٌ عَلَيْهِمْ أَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ 
> - 2:87  فَفَرِيقًا كَذَّبْتُمْ
> - 2:92 ثُمَّ اتَّخَذْتُمُ الْعِجْلَ
> - 14:7 لَئِن شَكَرْتُمْ
> - 14:7 وَلَئِن كَفَرْتُمْ

# Present/Future Tense

## Signs 

> - Starts with ta: 2nd person (you do)-
> - Starts with ya: 3rd person (they/he/she do/does)-
> - Starts with aa: I do-
> - Starts with naa: We do-نَعْبُدُ 

## Second Person

> - 2:6  لَمْ تُنذِرْهُمْ
> - 2:8 مَن يَقُولُ آمَنَّا
> - 

## Third Person

> -2:4 الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ وَيُقِيمُونَ الصَّلَاةَ وَمِمَّا رَزَقْنَاهُمْ يُنفِقُونَ



# Sign of Number

وا - Plural (past)

ونَ -Plural (present)

<div class="container">
<div class="col">
> - يَقُولُ
> - قَالُوا
> - يَسْتَهْزِئُ 
> - يَشْعُرُونَ 
> -  آمَنُوا
> - ذَهَبَ
</div>
<div class="col">
> - لَّا يُبْصِرُونَ
> - يَخْطَفُ
> - قَامُوا ۚ
> - خَلَقَكُمْ
> - جَعَلَ
> - وَأَنزَلَ
</div>
<div class="col">
> -  تَفْعَلُوا
> - عَمِلُوا
> - كَفَرُوا
> - فَيَقُولُونَ 
> - أَرَادَ 
> - يَنقُضُونَ 
> - يَقْطَعُونَ
> - أَمَرَ
</div>
</div>


## Signs of Gender

# Common Words

## Min

## Maa

## Fii

## Ilaa

# Pronouns

# Past Tense

# Passive

# Other Tenses

# Doer 

> - 2:5 وَأُولَٰئِكَ هُمُ الْمُفْلِحُونَ
> - 

# Maf'ul

# Tool / Instrument

# Place/Time 

# Command Patterns

# One-lettered Verbs

# Degree